packages:
  - "apps/web"
  - "apps/client"
  - "apps/admin"
  - "apps/server"
  - "apps/mobile"
  - "packages/*"

peerDependencyRules:
  allowedVersions:
    typescript: ">=6"

allowBuilds:
  es5-ext: true
  esbuild: true
  sharp: true
