import { useEffect, useState } from "react";
import { Box, Typography, Stack } from "@mui/material";
import { motion, AnimatePresence } from "framer-motion";

const MotionBox = motion.create(Box);

const API_URL = import.meta.env.VITE_API_URL ?? "http://localhost:4000";

interface Activity {
  text: string;
  ago: string;
  color: string;
}

const FALLBACK_POOL: Omit<Activity, "ago">[] = [
  { text: "New project briefed", color: "#10B981" },
  { text: "Spec generated by AI engine", color: "#6C63FF" },
  { text: "Sprint kicked off", color: "#00D4AA" },
  { text: "Milestone delivered", color: "#F59E0B" },
  { text: "Client onboarded", color: "#10B981" },
  { text: "Code review approved", color: "#8B85FF" },
  { text: "QA cycle completed", color: "#00D4AA" },
  { text: "Production deploy successful", color: "#10B981" },
];

const FALLBACK_TIMES = ["just now", "2 min ago", "8 min ago", "23 min ago", "1 hr ago", "3 hrs ago"];

function rand<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]!;
}

function timeAgo(iso: string): string {
  const ms = Date.now() - new Date(iso).getTime();
  if (ms < 0 || isNaN(ms)) return "just now";
  const min = Math.floor(ms / 60000);
  if (min < 1) return "just now";
  if (min < 60) return `${min} min ago`;
  const hr = Math.floor(min / 60);
  if (hr < 24) return `${hr} hr${hr > 1 ? "s" : ""} ago`;
  const day = Math.floor(hr / 24);
  return `${day} day${day > 1 ? "s" : ""} ago`;
}

export default function ActivityTicker() {
  const [events, setEvents] = useState<Activity[]>([]);
  const [idx, setIdx] = useState(0);

  // Fetch real events; gracefully fall back to synthetic pool
  useEffect(() => {
    let cancelled = false;
    const ctrl = new AbortController();
    fetch(`${API_URL}/api/v1/activity`, { signal: ctrl.signal })
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then((data) => {
        if (cancelled) return;
        const real = (data.events ?? []).map((e: any) => ({
          text: e.text,
          color: e.color ?? "#6C63FF",
          ago: timeAgo(e.ts),
        }));
        if (real.length > 0) setEvents(real);
        else setEvents(FALLBACK_POOL.map((p) => ({ ...p, ago: rand(FALLBACK_TIMES) })));
      })
      .catch(() => {
        if (cancelled) return;
        setEvents(FALLBACK_POOL.map((p) => ({ ...p, ago: rand(FALLBACK_TIMES) })));
      });
    return () => {
      cancelled = true;
      ctrl.abort();
    };
  }, []);

  // Cycle through events
  useEffect(() => {
    if (events.length === 0) return;
    const interval = setInterval(() => {
      setIdx((i) => (i + 1) % events.length);
    }, 4000);
    return () => clearInterval(interval);
  }, [events.length]);

  const activity = events[idx];
  if (!activity) return null;

  return (
    <Stack
      direction="row"
      spacing={1.5}
      sx={{ alignItems: "center",
        display: "inline-flex",
        px: 2,
        py: 1,
        borderRadius: 99,
        bgcolor: "rgba(108, 99, 255, 0.06)",
        border: "1px solid rgba(108, 99, 255, 0.15)",
        backdropFilter: "blur(8px)",
      }}
    >
      <Box
        sx={{
          width: 8,
          height: 8,
          borderRadius: "50%",
          bgcolor: activity.color,
          boxShadow: `0 0 10px ${activity.color}`,
          animation: "pulse 2s infinite",
          "@keyframes pulse": {
            "0%, 100%": { opacity: 1 },
            "50%": { opacity: 0.4 },
          },
        }}
      />
      <Typography sx={{ fontFamily: "monospace", fontSize: "0.65rem", letterSpacing: "0.1em", color: "text.secondary", opacity: 0.5, textTransform: "uppercase" }}>
        LIVE
      </Typography>
      <AnimatePresence mode="wait">
        <MotionBox
          key={activity.text + activity.ago}
          initial={{ opacity: 0, y: 6 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -6 }}
          transition={{ duration: 0.25 }}
          sx={{ display: "flex", alignItems: "center", gap: 1 }}
        >
          <Typography sx={{ fontSize: "0.8rem", color: "text.primary" }}>
            {activity.text}
          </Typography>
          <Typography sx={{ fontFamily: "monospace", fontSize: "0.65rem", color: "text.secondary", opacity: 0.5 }}>
            {activity.ago}
          </Typography>
        </MotionBox>
      </AnimatePresence>
    </Stack>
  );
}
